### ISSUE TITLE
Panic when drawing out of bound

### ISSUE THREAD

**Issue by tommythorn** [vleue/bevmnist#2]
I don't have time to investigate right now, but I noticed a panic if you draw over the edge (eg. mouse-down and move down beyond the border).

```
RUST_BACKTRACE=1 cargo run 
    Finished dev [unoptimized + debuginfo] target(s) in 0.15s
     Running `target/debug/bevmnist`
Nov 21 02:50:28.775  WARN wgpu_core::instance: Missing internal features: ROBUST_BUFFER_ACCESS
Nov 21 02:50:28.969  WARN wgpu_core::device: Failed to parse shader SPIR-V code: UnsupportedBuiltIn(4)
Nov 21 02:50:28.969  WARN wgpu_core::device: Shader module will not be validated
Nov 21 02:50:29.108  WARN wgpu_core::device: Failed to parse shader SPIR-V code: UnsupportedBuiltIn(4)
Nov 21 02:50:29.108  WARN wgpu_core::device: Shader module will not be validated
Nov 21 02:50:29.220  WARN wgpu_core::device: Failed to parse shader SPIR-V code: UnsupportedBuiltIn(4)
Nov 21 02:50:29.220  WARN wgpu_core::device: Shader module will not be validated
thread 'Compute Task Pool (4)' panicked at 'index out of bounds: the len is 1440000 but the index is 1441032', src/main.rs:200:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
   1: core::panicking::panic_fmt
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:85
   2: core::panicking::panic_bounds_check
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:62
   3: <usize as core::slice::index::SliceIndex<[T]>>::index_mut
             at /Users/tommy/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/slice/index.rs:261
   4: core::slice::index::<impl core::ops::index::IndexMut<I> for [T]>::index_mut
             at /Users/tommy/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/slice/index.rs:26
   5: <alloc::vec::Vec<T> as core::ops::index::IndexMut<I>>::index_mut
             at /Users/tommy/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/alloc/src/vec.rs:1994
   6: bevmnist::set_pixel
             at ./src/main.rs:200
   7: bevmnist::drawing
             at ./src/main.rs:185
...
```

**Comment by tommythorn** [comment]
The WASM version seems to freeze when I try it here.

**Comment by mockersf** [comment]
thank you, should be fixed now!
